### ISSUE TITLE
Text Overflow in CupertinoListTile

### ISSUE THREAD

**Issue by matissePe** [ivirtex/cupertino_lists#1]
Hi, despite several attempts, it seems impossible to handle text overflow in a CupertinoListTile.
I would like to put the too long text on several lines.

Is there any solution ?

<img width="382" alt="Capture d’écran 2022-09-01 à 22 47 13" src="https://user-images.githubusercontent.com/46610133/188009470-3f3a9e48-62f5-4e1a-bdb5-17c44624d84c.png">

**Comment by ivirtex** [comment]
Hi, you can use `ConstrainedBox` and `maxLines` property of the Text:
```dart
CupertinoListTile(
  title: ConstrainedBox(
    constraints: const BoxConstraints(maxWidth: 200),
    child: const Text(
      'text that overflows',
      maxLines: 3,
    ),
  ),
),
```

Let me know if you have any questions.

**Comment by matissePe** [comment]
I just tried your solution, but it doesn't work.
Extra words just don't appear

<img width="393" alt="Capture d’écran 2022-09-02 à 18 42 28" src="https://user-images.githubusercontent.com/46610133/188200064-c79890d6-0c57-4a0d-85dd-5f6d88007658.png">

**Comment by ivirtex** [comment]
Could you send me the implementation of your screen? You may be enforcing additional constraints.

**Comment by matissePe** [comment]
Your solution works ! Sorry it was a mistake on my side.
Thanks a lot for your help.
